name: llama_cpp
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - ipykernel
  - setuptools
  - wheel
  - pip:
      - llama-cpp-python==0.3.9
      - langchain==0.3.25
      - langchain-core==0.3.60
      - langchain-community==0.3.24
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.42
      - huggingface-hub==0.31.4
      - pydantic==2.11.4
      - pydantic-settings==2.9.1
      - dataclasses-json==0.6.7
      - faiss-cpu==1.11.0
      - numpy==2.2.6
      - requests==2.32.3
      - aiohttp==3.11.18
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - python-dotenv==1.1.0
